# This file is part of the cribbagehelper package.
# Copyright (C) 2026 James W. Johnson (giganano9@gmail.com)
# License: MIT License. See LICENSE under top-level direcotry
# at: https://github.com/giganano/cribbagehelper.git

THIS_DIR := ./cribbagehelper/forecast
include ../../common.mk
