# This file is part of the cribbagehelper package.
# Copyright (C) 2026 James W. Johnson (giganano0@gmail.com)
# License: MIT License. See LICENSE in top-level directory
# at: https://github.com/giganano/cribbagehelper.git

THIS_DIR := "./cribbagehelper/core/hand/tests"
include ../../../../common.mk
